# Generated by Django 4.0.1 on 2022-01-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_newuser_age_alter_newuser_family_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='name',
        ),
        migrations.AddField(
            model_name='newuser',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='occu_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='pin',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='tel',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
