# Generated by Django 4.0.1 on 2022-03-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_newuser_occu_type_alter_newuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
