# Generated by Django 4.0.1 on 2022-05-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_newuser_is_verify_alter_newuser_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verifycodelog',
            old_name='timestamp',
            new_name='send_at',
        ),
        migrations.RemoveField(
            model_name='verifycodelog',
            name='activity',
        ),
    ]
