# Generated by Django 4.0.1 on 2022-05-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_verifycodelog_ref_code_alter_newuser_is_verify_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifycodelog',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
