# Generated by Django 4.0.1 on 2022-05-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_verifycodelog_is_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifycodelog',
            name='is_used',
        ),
        migrations.AddField(
            model_name='verifytokenlog',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
