# Generated by Django 4.0.1 on 2022-05-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_verifycodelog_is_used_verifytokenlog_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifycodelog',
            name='is_used',
            field=models.BooleanField(default=True),
        ),
    ]
