# Generated by Django 4.0.1 on 2022-05-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_verifycodelog_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifycodelog',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verifytokenlog',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
