# Generated by Django 4.0.1 on 2022-05-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_verifycodelog_count_verifytokenlog_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifytokenlog',
            name='count',
            field=models.SmallIntegerField(default=0),
        ),
    ]
