# Generated by Django 4.0.1 on 2022-05-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_verifytokenlog_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='age',
        ),
        migrations.AddField(
            model_name='newuser',
            name='born_year',
            field=models.IntegerField(null=True),
        ),
    ]
