# Generated by Django 4.0.1 on 2022-05-10 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_verifycodelog_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.province'),
        ),
    ]
