# Generated by Django 4.0.1 on 2022-01-13 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestionboard',
            name='sugg_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendboard',
            name='ach_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.achievement'),
        ),
        migrations.AddField(
            model_name='recommendboard',
            name='recomm_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialstatementplan',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.month'),
        ),
        migrations.AddField(
            model_name='financialstatementplan',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
        migrations.AddField(
            model_name='dailyflowsheet',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyflow',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
        migrations.AddField(
            model_name='dailyflow',
            name='ds_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dailyflowsheet'),
        ),
        migrations.AddField(
            model_name='category',
            name='ftype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.financialtype'),
        ),
        migrations.AddField(
            model_name='category',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='balancesheetlog',
            name='bsheet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.balancesheet'),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='achievement',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debt',
            name='bsheet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.balancesheet'),
        ),
        migrations.AddField(
            model_name='budget',
            name='fplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.financialstatementplan'),
        ),
        migrations.AddField(
            model_name='asset',
            name='bsheet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.balancesheet'),
        ),
    ]
