# Generated by Django 4.0.1 on 2022-01-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialstatementplan',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='financialstatementplan',
            name='start',
            field=models.DateField(),
        ),
    ]
