# Generated by Django 4.0.1 on 2022-01-26 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_financialstatementplan_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='dailyflow',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='knowledgearticle',
            name='body',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='image',
        ),
    ]
