# Generated by Django 4.0.1 on 2022-02-18 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_category_icon_remove_dailyflow_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debt',
            old_name='settlement',
            new_name='suspend',
        ),
    ]
