# Generated by Django 4.0.1 on 2022-02-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_settlement_debt_suspend'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.FilePathField(default='shield-alt'),
        ),
    ]
