# Generated by Django 4.0.1 on 2022-02-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialstatementplan',
            name='id',
            field=models.CharField(max_length=23, primary_key=True, serialize=False),
        ),
    ]
