# Generated by Django 4.0.1 on 2022-02-26 14:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_budget_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='cat_id',
            field=models.ForeignKey(default=datetime.datetime(2022, 2, 26, 14, 28, 6, 233442, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='api.category'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('cat_id', 'fplan')},
        ),
    ]
