# Generated by Django 4.0.1 on 2022-02-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_budget_cat_id_alter_budget_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
