# Generated by Django 4.0.1 on 2022-02-28 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_alter_budget_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyflow',
            name='detail',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dailyflow',
            name='id',
            field=models.CharField(max_length=21, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dailyflowsheet',
            name='id',
            field=models.CharField(max_length=19, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'method',
            },
        ),
        migrations.AddField(
            model_name='dailyflow',
            name='method',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.method'),
            preserve_default=False,
        ),
    ]
