# Generated by Django 4.0.1 on 2022-02-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_dailyflow_detail_alter_dailyflow_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='icon',
            field=models.CharField(default='money-bill', max_length=20),
        ),
    ]
