# Generated by Django 4.0.1 on 2022-02-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_method_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='frequency',
            field=models.CharField(choices=[('DLY', 'Daily'), ('WLY', 'Weekly'), ('MLY', 'Monthly'), ('ALY', 'Annually')], default='MLY', max_length=3),
        ),
    ]
