# Generated by Django 4.0.1 on 2022-03-01 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_budget_frequency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyflow',
            old_name='ds_id',
            new_name='df_id',
        ),
    ]
