# Generated by Django 4.0.1 on 2022-03-05 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_dailyflowsheet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='bsheet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='api.balancesheet'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='bsheet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='api.balancesheet'),
        ),
    ]
