# Generated by Django 4.0.1 on 2022-03-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_asset_cat_id_alter_debt_cat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='benefit_type',
            field=models.CharField(choices=[('ITR', 'Interest'), ('DIV', 'Dividend'), ('RTF', 'Rental Fee'), ('SEL', 'Sell')], default=None, max_length=3, null=True),
        ),
    ]
