# Generated by Django 4.0.1 on 2022-03-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_asset_benefit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='benefit_type',
            field=models.CharField(choices=[('ITR', 'Interest'), ('DIV', 'Dividend'), ('RTF', 'Rental Fee'), ('SEL', 'Sell')], max_length=3, null=True),
        ),
    ]
