# Generated by Django 4.0.1 on 2022-03-06 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_asset_benefit_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyflow',
            old_name='category_id',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='dailyflow',
            name='df_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='api.dailyflowsheet'),
        ),
    ]
