# Generated by Django 4.0.1 on 2022-03-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_rename_category_id_dailyflow_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debt',
            old_name='balance',
            new_name='used_balance',
        ),
    ]
