# Generated by Django 4.0.1 on 2022-03-06 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_rename_balance_debt_used_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='balance',
            new_name='used_balance',
        ),
        migrations.RenameField(
            model_name='debt',
            old_name='used_balance',
            new_name='balance',
        ),
    ]
