# Generated by Django 4.0.1 on 2022-03-07 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_budget_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='api.category'),
        ),
        migrations.AlterField(
            model_name='dailyflow',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='api.category'),
        ),
    ]
