# Generated by Django 4.0.1 on 2022-03-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_debt_debt_term'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancesheetlog',
            name='asset_value',
        ),
        migrations.RemoveField(
            model_name='balancesheetlog',
            name='benefit_value',
        ),
        migrations.RemoveField(
            model_name='balancesheetlog',
            name='debt_interest',
        ),
        migrations.AlterField(
            model_name='asset',
            name='benefit_value',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='recent_value',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='balancesheetlog',
            name='debt_balance',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budget',
            name='budget_per_period',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budget',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dailyflow',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='debt',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='debt',
            name='minimum',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='financialgoal',
            name='goal',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='financialgoal',
            name='progress_per_period',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='financialgoal',
            name='total_progress',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
