# Generated by Django 4.0.1 on 2022-03-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_category_ftype_defaultcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='used_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
