# Generated by Django 4.0.1 on 2022-03-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_budget_used_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheetlog',
            name='asset_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
