# Generated by Django 4.0.1 on 2022-03-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_financialgoal_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='financialgoal',
            name='id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
