# Generated by Django 4.0.1 on 2022-03-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_category_isdeleted_alter_financialgoal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='id',
            field=models.CharField(max_length=19, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='budget',
            name='id',
            field=models.CharField(max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(max_length=17, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dailyflow',
            name='id',
            field=models.CharField(max_length=23, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='debt',
            name='id',
            field=models.CharField(max_length=19, primary_key=True, serialize=False),
        ),
    ]
