# Generated by Django 4.0.1 on 2022-03-14 10:38

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_asset_id_alter_budget_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget_per_period',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[api.models.validate_ispositive]),
        ),
        migrations.AlterField(
            model_name='financialgoal',
            name='id',
            field=models.CharField(max_length=17, primary_key=True, serialize=False),
        ),
    ]
