# Generated by Django 4.0.1 on 2022-03-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_asset_benefit_value_alter_asset_recent_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='imp_ranking',
        ),
    ]
