# Generated by Django 4.0.1 on 2022-04-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_remove_debt_imp_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='source',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
