# Generated by Django 4.0.1 on 2022-04-13 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_asset_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='used_balance',
        ),
    ]
