# Generated by Django 4.0.1 on 2022-04-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_knowledgearticle_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgearticle',
            name='image',
        ),
    ]
