# Generated by Django 4.0.1 on 2022-04-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_remove_knowledgearticle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticle',
            name='image',
            field=models.ImageField(default=0, upload_to='media/'),
            preserve_default=False,
        ),
    ]
