# Generated by Django 4.0.1 on 2022-04-13 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_knowledgearticle_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knowledgearticle',
            old_name='creator',
            new_name='author',
        ),
    ]
