# Generated by Django 4.0.1 on 2022-04-13 16:30

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_rename_creator_knowledgearticle_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticle',
            name='isexclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='image',
            field=models.ImageField(upload_to=api.models.nameFile),
        ),
    ]
