# Generated by Django 4.0.1 on 2022-04-14 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0053_viewer_delete_view_alter_balancesheetlog_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgearticle',
            name='like',
        ),
        migrations.CreateModel(
            name='Liker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.knowledgearticle')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'liker',
            },
        ),
    ]
