# Generated by Django 4.0.1 on 2022-04-14 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_remove_knowledgearticle_like_liker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liker',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='api.knowledgearticle'),
        ),
    ]
