# Generated by Django 4.0.1 on 2022-04-14 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0055_alter_liker_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExclusiveArticleOwner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusive_article', to='api.knowledgearticle')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exclusive_article_owner',
            },
        ),
    ]
