# Generated by Django 4.0.1 on 2022-04-14 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_exclusivearticleowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticle',
            name='upload_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
